// RootLayout.js (Server-side component)
import './globals.css';
import { Poppins } from 'next/font/google';
import { Abhaya_Libre } from 'next/font/google';

const abhayaLibre = Abhaya_Libre({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-abhaya',
  weight: ['400', '500', '600', '700', '800']
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Skin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${abhayaLibre.variable} font-poppins`}>
        {children}
      </body>
    </html>
  );
}
